
# Procesamiento de la Carta Marina de Córdoba 2019

## Descripción

Este notebook tiene como objetivo reconstruir y documentar el proceso de extracción de datos de la Carta Marina de Córdoba correspondiente a las elecciones de 2019.

El desarrollo se basa en el trabajo realizado en el repositorio **Carta Marina Córdoba 2017** de avdata99 (https://github.com/avdata99/carta-marina-2017/tree/master).

En esta etapa el trabajo se concentra exclusivamente en la Carta Marina 2019.

## Flujo de trabajo


1. PDF
2. TXT (pdftotext -layout)
3. CSV de mesas/escuelas/electores
4. Geolocalización de escuelas
5. CSV geolocalizado
6. Mapas y análisis


**Productos esperados**

- `LugaresDeVotacion-elecciones-2015.pdf`
- `carta-marina-cordoba-2015.txt`
- `escuelas-elecciones-2015-cordoba.csv`
- `escuelas-elecciones-2015-cordoba-clean.csv` (si requiere correcciones)

0. Dependencias

In [2]:
from google.colab import files
import pandas as pd
from pathlib import Path

In [3]:
!apt-get update -qq
!apt-get install -y -qq poppler-utils

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
(Reading database ... 118243 files and directories currently installed.)
Preparing to unpack .../libpoppler-private-dev_22.02.0-2ubuntu0.13_amd64.deb ...
Unpacking libpoppler-private-dev:amd64 (22.02.0-2ubuntu0.13) over (22.02.0-2ubuntu0.12) ...
Preparing to unpack .../libpoppler-dev_22.02.0-2ubuntu0.13_amd64.deb ...
Unpacking libpoppler-dev:amd64 (22.02.0-2ubuntu0.13) over (22.02.0-2ubuntu0.12) ...
Preparing to unpack .../libpoppler118_22.02.0-2ubuntu0.13_amd64.deb ...
Unpacking libpoppler118:amd64 (22.02.0-2ubuntu0.13) over (22.02.0-2ubuntu0.12) ...
Selecting previously unselected package poppler-utils.
Preparing to unpack .../poppler-utils_22.02.0-2ubuntu0.13_amd64.deb ...
Unpacking poppler-utils (22.02.0-2ubuntu0.13) ...
Setting up libpoppler118:amd64 (22.02.0-2ubuntu0.13) ...
Setting up poppler-utils (22.02.0-2ubuntu0.13) ...
Setting up libpoppler-dev:amd64 (22.02.0-2ubuntu0.13) ...
Setting up libpoppler-private-dev:amd64 (22.02.0-2ubuntu0.13) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.13) ...
/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

#1. Carga del PDF

In [4]:
archivo = files.upload()

nombre_archivo = next(iter(archivo))

print(f"Archivo cargado: {nombre_archivo}")

Saving 2019.pdf to 2019.pdf
Archivo cargado: 2019.pdf

#2. PDF a TXT

In [5]:
nombre_txt = Path(nombre_archivo).with_suffix(".txt")

!pdftotext -layout "{nombre_archivo}" "{nombre_txt}"

print(f"Archivo generado: {nombre_txt}")

Archivo generado: 2019.txt

#3. TXT a CSV



```
Leer línea
    │
    ├── ¿Es un encabezado o número de página?
    │      └── Sí → ignorar
    │
    ├── ¿Es una sección?
    │      └── Sí → actualizar sección
    │
    ├── ¿Es un circuito?
    │      └── Sí → actualizar circuito e iniciar lectura de establecimientos
    │
    ├── ¿Es el resumen del circuito?
    │      └── Sí → finalizar lectura del circuito
    │
    ├── ¿Está vacía?
    │      └── Sí → ignorar
    │
    ├── ¿Estamos dentro de un circuito?
    │      └── No → continuar
    │
    └── Procesar establecimiento
           ├── Ignorar líneas "asociada a"
           ├── Reconstruir el nombre del establecimiento
           ├── Extraer mesas y electores
           ├── Validar continuidad de mesas
           └── Guardar registro
```

##Inspeccion del TXT

In [6]:
path = f"/content/{nombre_txt}"

with open(path, "r", encoding="utf-8") as f:
    raw = f.read()

lines = raw.splitlines()

print(f"Cantidad total de líneas: {len(lines)}")
print("\nPrimeras 10 líneas:\n")

for i, linea in enumerate(lines[:10], start=1):
    print(i, repr(linea))
print ("...")
print ("...")
print ("...")
print ("...")
for i, linea in enumerate(raw.splitlines()[-10:], start=len(raw.splitlines())-9):
    print(i, repr(linea))

Cantidad total de líneas: 6281

Primeras 10 líneas:

1 '                                                  DISTRITO CORDOBA'
2 '                            ELECCIONES GENERALES - 27 de Octubre de 2019'
3 '                             Informe de Establecimientos, Mesas y Electores Habilitados'
4 ''
5 'Sección 1 - CAPITAL'
6 ''
7 'Circuito:1 - SECCIONAL PRIMERA                                              Cant   Desde / hasta              Cant'
8 '                                                                           Mesas                            Electores'
9 'CENTRO EDUC.NIVEL MEDIO ADULTO - DEAN FUNES 417 CAPITAL - CORDOBA           7       0001 a 0007                 2.415'
10 ''
...
...
...
...
6272 ''
6273 '              Mesas Habilitadas:                                                                     8.750'
6274 ''
6275 '              Electores Habilitados                                                              2.946.060'
6276 ''
6277 ''
6278 ''
6279 ''
6280 'oct 2, 2019                                                                                        Pag.91 de91'
6281 ''

In [7]:
print("Saltos de línea \\n:", raw.count("\n"))
print("Saltos de página \\f:", raw.count("\f"))

print("Con split('\\n'):", len(raw.split("\n")))
print("Con splitlines():", len(raw.splitlines()))

Saltos de línea \n: 6190
Saltos de página \f: 91
Con split('\n'): 6191
Con splitlines(): 6281

##Inicialización de variables

In [33]:
# =====================================
# Inicialización de variables del parser
# =====================================

# Sección electoral (equivale al departamento de la provincia)
seccion_nro = 0
seccion_name = ""

# Circuito electoral dentro de la sección.
# Puede contener letras (ej.: 4A, 4B, 4C), por eso se almacena como texto.
circuito_nro = ""
circuito_name = ""

# Estado actual del parser.
# Cuando vale "escuelas", las líneas leídas corresponden a establecimientos.
imin = ""

# Contador de líneas procesadas del archivo TXT.
cnt = 0

# Contador de errores (heredado del parser original).
errores = 0

# Lista donde se almacenan todos los establecimientos extraídos.
# Cada elemento es un diccionario con la información de un establecimiento.
escuelas = []

# Registra las discontinuidades detectadas en la numeración de mesas.
# Se utiliza como control de calidad, pero no interrumpe la ejecución.
discontinuidades = []

# Última mesa procesada.
# Permite verificar que la numeración de mesas sea continua.
last_mesa = 0

# ============================
# Variables de diagnóstico
# ============================

# Cantidad de números de página ignorados.
paginas_ignoradas = 0

# Cantidad de encabezados "DISTRITO CORDOBA" ignorados.
distritos_ignorados = 0

# Cantidad de encabezados "ELECCIONES 2015" ignorados.
elecciones_ignoradas = 0

# Cantidad de encabezados "Informe de Establecimientos" ignorados.
informes_ignorados = 0

# Almacena las filas que no pudieron procesarse correctamente,
# junto con la información necesaria para su revisión.
filas_con_error = []

print(f"Contador inicial: {cnt}")

Contador inicial: 0

##Ciclo for

In [34]:
for linea in lines:
    cnt += 1

    # Ignorar número de página
    if "Página" in linea or "Pag." in linea:
        paginas_ignoradas += 1
        continue

    # Ignorar encabezados
    if linea.strip() == "DISTRITO CORDOBA":
        distritos_ignorados += 1
        continue

    if "ELECCIONES" in linea:
        elecciones_ignoradas += 1
        continue

    if "Informe de Establecimientos" in linea:
        informes_ignorados += 1
        continue

    if "Mesas" in linea and "Electores" in linea:
        informes_ignorados += 1
        continue

    # Detectar sección
    if linea.startswith("Sección "):
        contenido = linea.removeprefix("Sección ").strip()
        partes = contenido.split("-", 1)

        seccion_nro = int(partes[0].strip())
        seccion_name = partes[1].strip()

        imin = ""
        continue

    # Detectar circuito
    if linea.startswith("Circuito:"):
        contenido = linea.removeprefix("Circuito:").strip()
        partes = contenido.split("-", 1)

        circuito_nro = partes[0].strip()

        # En la misma línea aparecen los títulos de otras columnas
        partes_nombre = partes[1].split("       ")
        circuito_name = partes_nombre[0].strip()

        imin = "escuelas"
        continue

    # Detectar el final del listado de escuelas
    # Las líneas vacías se ignoran, pero no cierran el circuito
    if linea == "":
       continue

    # Solo el resumen cierra realmente el circuito
    if linea.startswith("Resumen del Circuito"):
        imin = ""
        continue

    # Procesar escuelas
    if imin == "escuelas":
        partes = linea.split("    ")

        # Conservar solo fragmentos con contenido
        datos = [x.strip() for x in partes if x.strip() != ""]

        print(f"{cnt} -- {datos}")

        if len(datos) == 1 and "asociada a" in datos[0]:
            continue



        establecimiento = " ".join(datos[:-3])
        cant_mesas = int(datos[-3])

        rango_mesas = datos[-2].split(" a ")
        mesa_desde = int(rango_mesas[0])
        mesa_hasta = int(rango_mesas[1])


        if mesa_desde != last_mesa + 1:
            discontinuidades.append({
              "linea": cnt,
              "esperada": last_mesa + 1,
              "encontrada": mesa_desde,
              "establecimiento": establecimiento
          })
            #raise ValueError(
                #f"Mesa inválida en línea {cnt}: "
                #f"empieza en {mesa_desde}, "
                #f"pero la anterior terminó en {last_mesa}"
            #)

        last_mesa = mesa_hasta

        cant_electores = int(datos[-1].replace(".", ""))

        elem = {
            "seccion_nro": seccion_nro,
            "seccion_name": seccion_name,
            "circuito_nro": circuito_nro,
            "circuito_name": circuito_name,
            "establecimiento": establecimiento.replace(",", "."),
            "cant_mesas": cant_mesas,
            "desde": mesa_desde,
            "hasta": mesa_hasta,
            "electores": cant_electores,
        }

        escuelas.append(elem)
        print(f"Contador inicial: {cnt}")

9 -- ['CENTRO EDUC.NIVEL MEDIO ADULTO - DEAN FUNES 417 CAPITAL - CORDOBA', '7', '0001 a 0007', '2.415']
Contador inicial: 9
11 -- ['ESC NUESTRA SEÑORA DEL HUERTO - BELGRANO 269 CAPITAL - CORDOBA', '12', '0008 a 0019', '4.128']
Contador inicial: 11
13 -- ['COL NAC DE MONSERRAT - OBISPO TREJO 294 CAPITAL - CORDOBA', '18', '0020 a 0037', '6.192']
Contador inicial: 13
15 -- ['ESC SANTA TERESA DE JESUS - OBISPO TREJO Y SANABRIA 160 CAPITAL -', '10', '0038 a 0047', '3.440']
Contador inicial: 15
21 -- ['ESC JUAN BAUTISTA ALBERDI - GRAL PAZ 488 CAPITAL - CORDOBA', '18', '0048 a 0065', '6.176']
Contador inicial: 21
27 -- ['ESC JERONIMO LUIS DE CABRERA - SANTA ROSA 650 CAPITAL - CORDOBA', '15', '0066 a 0080', '5.220']
Contador inicial: 27
29 -- ['IPEM N° 270 GRAL M BELGRANO - DEAN FUNES 850 CAPITAL - CORDOBA', '11', '0081 a 0091', '3.817']
Contador inicial: 29
31 -- ['ESC SANTO TOMAS - CASEROS 745 CAPITAL - CORDOBA', '8', '0092 a 0099', '2.776']
Contador inicial: 31
33 -- ['ESC NORMAL ALEJANDRO CARBO - AV COLON 951 CAPITAL - CORDOBA', '13', '0100 a 0112', '4.511']
Contador inicial: 33
35 -- ['ESC MARIANO MORENO - SANTA ROSA ESQ SANTA FE 1299 CAPITAL - CORDOBA', '13', '0113 a 0125', '4.511']
Contador inicial: 35
41 -- ['COL NACIONAL DEAN FUNES - PERU 10 B°N CORDOBA CAPITAL - CORDOBA', '20', '0126 a 0145', '6.979']
Contador inicial: 41
43 -- ['IPET N°66 DR JOSE A BALSEIRO - HIPOLITO YRIGOYEN 258 B°N CORDOBA CAPITAL', '14', '0146 a 0159', '4.872']
Contador inicial: 43
45 -- ['ESC GDOR ALVAREZ - C ARENAL 699 B°R MARTINEZ CAPITAL - CORDOBA', '9', '0160 a 0168', '3.132']
Contador inicial: 45
47 -- ['FAC DE CIENCIAS ECONOMICAS - AV VALPARAISO CDAD UNIVERSITARIA CAPITAL -', '10', '0169 a 0178', '3.480']
Contador inicial: 47
49 -- ['IPEM 38 FRANC. PABLO DE MAURO - PAUNERO Y ARENAL CAPITAL - CORDOBA', '9', '0179 a 0187', '3.132']
Contador inicial: 49
55 -- ['ESC ERNESTO BANCALARI - MONTERROSO 4597 B° ARTIGAS- CAPITAL - CORDOBA', '7', '0188 a 0194', '2.429']
Contador inicial: 55
57 -- ['ESC ALMAFUERTE - CHANETON 390 B°SAN FERNANDO CAPIT - CORDOBA', '7', '0195 a 0201', '2.429']
Contador inicial: 57
59 -- ['ESC COM R ECHEGOYEN - J I DIAZ 200 B°EJERCITO ARGENTINO - CORDOBA', '8', '0202 a 0209', '2.776']
Contador inicial: 59
61 -- ['ESC SAN FRANCISCO DE ASIS - GUARDADO 184 B°LAS FLORES -CAP - CORDOBA', '15', '0210 a 0224', '5.205']
Contador inicial: 61
63 -- ['ESC DANTE ALIGHIERI - JOSE JAVIER DIAZ 421 B°IPONA CAPITAL - CORDOBA', '15', '0225 a 0239', '5.201']
Contador inicial: 63
81 -- ['INST EDUC NTRA SEÑORA - INCA MANCO - 3450 B°JARDIN ESPINOSA - CORDOBA', '11', '0240 a 0250', '3.839']
Contador inicial: 81
83 -- ['ESC ING MASJOAN - P.L.DE CABRERA ESQ.TANTI 3070 B° V REVOL-CAPITAL -', '10', '0251 a 0260', '3.490']
Contador inicial: 83
85 -- ['COL NICOLAS BERROTARAN - ELIAS YOFRE - 1095 B°JARDIN-CAPITAL - CORDOBA', '11', '0261 a 0271', '3.839']
Contador inicial: 85
87 -- ['COL PARROQUIAL CRISTO REDENTOR - JUSTINIANO POSSE - 864 B°JARDIN-', '7', '0272 a 0278', '2.443']
Contador inicial: 87
89 -- ['JOVENES ARGENTINOS - BOTAFOGO 3448 - CORDOBA', '6', '0279 a 0284', '2.092']
Contador inicial: 89
95 -- ['ESC SAN JOSE DE CALASANZ - PIZARRO ESQ. NIVOLI INAUDI CAPITAL - CORDOBA', '6', '0285 a 0290', '2.088']
Contador inicial: 95
97 -- ['IPEN 310- PUERTO ARGENTINO - LUDUEÑA Y SARGENTO RIOS B°INAUDI,CAPITAL -', '8', '0291 a 0298', '2.777']
Contador inicial: 97
103 -- ['COL VILLA EUCARISTICA - CNO A SAN CARLOS KM.5 1/2 B°V EUCARISTICA CAP -', '8', '0299 a 0306', '2.472']
Contador inicial: 103
109 -- ['ESC.SABIN - DDE.CMO.S.ANTONIO KM 7 1/2,1KM.AL O. B°NUESTRO HOGAR III -', '9', '0307 a 0315', '2.899']
Contador inicial: 109
115 -- ['NSC.OSCAR RAUL MALVASIO - PUBLICA S/N MANZANA 49 B°OBISPO ANGELELLI -', '9', '0316 a 0324', '3.002']
Contador inicial: 115
121 -- ['ESC ESPAÑA - M BRAVO Y ENTRE RIOS B° ACOSTA CAPITAL - CORDOBA', '14', '0325 a 0338', '4.860']
Contador inicial: 121
123 -- ['ESC GRECIA - PEDERNERA 952 B°ALTAMIRA - CORDOBA', '11', '0339 a 0349', '3.817']
Contador inicial: 123
125 -- ['ESC PANAMERICANA - SOTO - 919 B° ACOSTA-CAPITAL - CORDOBA', '10', '0350 a 0359', '3.470']
Contador inicial: 125
127 -- ['ESC ESTANISLAO DEL CAMPO - ESTADOS UNIDOS Y RIO 1° 1208 B° ALTAMIRA', '5', '0360 a 0364', '1.735']
Contador inicial: 127
133 -- ['ESC MUNICIPAL A GASTALDI - S JERONIMO/ALMAGRO 5550 B° COLONIA LOLA -', '6', '0365 a 0370', '2.027']
Contador inicial: 133
135 -- ['ELENA LOPEZ LALLANA - AGUSTIN GARZON 5600 B°MIRALTA CAPITAL - CORDOBA', '10', '0371 a 0380', '3.370']
Contador inicial: 135
151 -- ['ESC 9 DE JULIO - JOSE A CABRERA° 5051 DEAN FUNES - CORDOBA', '6', '0381 a 0386', '1.851']
Contador inicial: 151
157 -- ['ESC PROVINCIA DE LA RIOJA - JUNIN 3480 B°MIRADOR CAPITAL - CORDOBA', '10', '0387 a 0396', '3.454']
Contador inicial: 157
159 -- ['ESC VICTOR MERCANTE - CAUCETE 4008 B°EMPALME CAPITAL - CORDOBA', '12', '0397 a 0408', '4.140']
Contador inicial: 159
161 -- ['ESC JUAN M DE PUEYRREDON - ANCASTI 4555 B°EMPALME CAPITAL - CORDOBA', '8', '0409 a 0416', '2.760']
Contador inicial: 161
163 -- ['INST SEC EMPALME GONZALEZ LACA - LAS ARRIAS 4043 B°EMPALME CAPITAL -', '5', '0417 a 0421', '1.725']
Contador inicial: 163
165 -- ['FRAY JUSTO STA MARÍA DE ORO - CALLAO 2320 B°1 DE MAYO CAPITAL - CORDOBA', '12', '0422 a 0433', '4.140']
Contador inicial: 165
167 -- ['IPEM 400 LOPEZ LALLANA - CORRIENTES 5583 B°PALADINI - CORDOBA', '6', '0434 a 0439', '2.070']
Contador inicial: 167
173 -- ['ESC CANONIGO PIÑERO - MARTIN C MALDONADO CAMPO LA RIVERA CAPITAL -', '6', '0440 a 0445', '2.058']
Contador inicial: 173
175 -- ['ESC MARTIN DE GÜEMES - OBPO CASTELLANOS 256 B°MULLER-CAPITAL -', '9', '0446 a 0454', '3.079']
Contador inicial: 175
177 -- ['BAC TEC DR F ESCARDO(IPEM 133) - CAMPO LA RIBERA CAPITAL - CORDOBA', '9', '0455 a 0463', '3.078']
Contador inicial: 177
179 -- ['IPEM 184-M.FRAGUEIRO - OB.CASTELLANO, 945 B°MULLER CAPITAL - CORDOBA', '10', '0464 a 0473', '3.420']
Contador inicial: 179
185 -- ['ESC TTE GRAL P RICCHIERI - BENJAMIN VIEL 2387 B°V BUSTOS CAPITAL -', '6', '0474 a 0479', '2.062']
Contador inicial: 185
187 -- ['IPEM 136 DR ALFREDO PALACIOS - CALINGASTA (ESQ TULUMBA) 5800 VILLA', '6', '0480 a 0485', '2.058']
Contador inicial: 187
193 -- ['ESC M COOPERATIVISMO ARGENTINO - M BRAVO Y PJE.MATHEU 5030 B°', '14', '0486 a 0499', '4.742']
Contador inicial: 193
199 -- ['ESC SANTA MARGARITA DE CORTONA - LOPEZ Y PLANES 2958 B°S VICENTE', '10', '0500 a 0509', '3.490']
Contador inicial: 199
201 -- ['ESC DGO F SARMIENTO - LOPEZ Y PLANES 2253 B°S VICENTE CAPITAL - CORDOBA', '14', '0510 a 0523', '4.873']
Contador inicial: 201
203 -- ['ESC PTE RIVADAVIA - AGUSTIN GARZON 1563 B°SVICENTE CAPITAL - CORDOBA', '12', '0524 a 0535', '4.176']
Contador inicial: 203
205 -- ['ESC MARIA IGNACIA NAVARRO DE L - CORRIENTES 2006 B°S VICENTE CAPITAL -', '9', '0536 a 0544', '3.132']
Contador inicial: 205
222 -- ['ESC. MADRE MARIA DEL TRANSITO - MANZANA 7, B° VILLA BOEDO - CORDOBA', '6', '0545 a 0550', '2.026']
Contador inicial: 222
228 -- ['ESCUELA HEROES DE MALVINAS - C/PUBLICA S/N (CNO VILLA POSSE) B° CIUDAD', '8', '0551 a 0558', '2.800']
Contador inicial: 228
230 -- ['ESC.PTE. JUAN D.PERÓN - MANZANA 47 B° V CIUDAD EVITA - CORDOBA', '7', '0559 a 0565', '2.450']
Contador inicial: 230
236 -- ['ESC TENIENTE GRAL ARAMBURU - GARIBALDI 710 B°ALTO GRAL PAZ - CORDOBA', '9', '0566 a 0574', '3.008']
Contador inicial: 236
238 -- ['COL SAN RAMON NONATO - AVDA PATRIA 282 B°ALTO GRAL PAZ - CORDOBA', '7', '0575 a 0581', '2.338']
Contador inicial: 238
244 -- ['ESC MUNICIPAL DR A SOBRAL - PUBLICA S/N° B°SANGRE Y SOL - CORDOBA', '1', '0582 a 0582', '306']
Contador inicial: 244
250 -- ['ESC VAN GELDEREN - CNO CHACRA DE LA MERCED KM 6 1/2 CAPITAL - CORDOBA', '1', '0583 a 0583', '221']
Contador inicial: 250
256 -- ['ESC RAMON J CARCANO - VIAMONTE 446 B°GRAL.PAZ CAPITAL - CORDOBA', '11', '0584 a 0594', '3.806']
Contador inicial: 256
258 -- ['ESC NORMAL GARZON AGULLA - VIAMONTE 150 B°GRAL.PAZ CAPITAL - CORDOBA', '15', '0595 a 0609', '5.179']
Contador inicial: 258
260 -- ['IPET N°10 COM MARTIN RIVADAVIA - 25 DE MAYO ESQ ROMA 1500 B°GRAL.PAZ', '10', '0610 a 0619', '3.450']
Contador inicial: 260
266 -- ['ESC GABRIELA MISTRAL - LEONOR DE TEJEDA 1353 B°JUNIORS CAPITAL -', '10', '0620 a 0629', '3.350']
Contador inicial: 266
268 -- ['ESC BRIGADIER C SAAVEDRA - ARENALES Y LA PLATA 900 B°JUNIORS CAPITAL -', '12', '0630 a 0641', '4.015']
Contador inicial: 268
274 -- ['ESC TRANSITO CACERES DE ALLEND - C/CHACRA DE LA MERCED KM 9 Y 1/2', '7', '0642 a 0648', '2.391']
Contador inicial: 274
290 -- ['ESC R GÜIRALDES - 24 DE SETIEMBRE 2400 B°YAPEYU CAPITAL - CORDOBA', '12', '0649 a 0660', '4.104']
Contador inicial: 290
292 -- ['ESC GDOR AMADEO SABATTINI - GERMANIA 5665 B°YAPEYU CAPITAL - CORDOBA', '12', '0661 a 0672', '4.094']
Contador inicial: 292
298 -- ['ESC JORGE NEWBERY (CIRC 7F) - MATIENZO 5895 BARRIO JORGE NEWBERY -', '1', '0673 a 0673', '112']
Contador inicial: 298
304 -- ['IPEM N° 22 JUAN FILLOY - CALLE DE LA CUECA 0 B°ALICIA RISLER - CORDOBA', '6', '0674 a 0679', '2.052']
Contador inicial: 304
306 -- ['ESC UNESCO - JUAN B JUSTO/AV N SRA D LOS MILAGROS 0 B° GUIÑAZU -', '14', '0680 a 0693', '4.781']
Contador inicial: 306
312 -- ['ESC MANUEL LUCERO - MANUEL LUCERO 560 B°ALTA CORD CAPITAL - CORDOBA', '19', '0694 a 0712', '6.650']
Contador inicial: 312
314 -- ['ESC PCIA DE ENTRE RIOS - TRAFALGAR 845 B°ALTA CORD CAPITAL - CORDOBA', '11', '0713 a 0723', '3.840']
Contador inicial: 314
316 -- ['INST CORAZON DE MARIA - A DEL VISO 445 B°ALTA CORD CAPITAL - CORDOBA', '14', '0724 a 0737', '4.886']
Contador inicial: 316
318 -- ['INST NUESTRA MADRE DE LA MERCE - M FRAGUEIRO 2389 B°ALTA CORD CAPITAL -', '13', '0738 a 0750', '4.537']
Contador inicial: 318
320 -- ['INST MANUEL LUCERO - LAVALLEJA 2257 B°ALTA CORD CAPITAL - CORDOBA', '8', '0751 a 0758', '2.792']
Contador inicial: 320
326 -- ['ESC J NEWBERY - ALBERTO MACIAS 451 B°J NEWBERY CAPITAL - CORDOBA', '1', '0759 a 0759', '10']
Contador inicial: 326
332 -- ['ESC PTE SARMIENTO - R SAENZ PEÑA 1211 B°COFICO CAPITAL - CORDOBA', '12', '0760 a 0771', '4.116']
Contador inicial: 332
334 -- ['ESC PCIA DE FORMOSA - RODRIGUEZ PEÑA 1548 B°COFICO CAPITAL - CORDOBA', '8', '0772 a 0779', '2.744']
Contador inicial: 334
336 -- ['ESC. GARCIA FAURE - JERONIMO LUIS DE CABRERA 834 B°COFICO CAPITAL -', '9', '0780 a 0788', '3.084']
Contador inicial: 336
342 -- ['ESC HONORATO LACONI - T DE IROBI 557 B°M DE SOBREMONTE - CORDOBA', '15', '0789 a 0803', '5.190']
Contador inicial: 342
344 -- ['ESC PETER PAN - P DE GUZMAN 131 B°M DE SOBREMONTE - CORDOBA', '15', '0804 a 0818', '5.190']
Contador inicial: 344
346 -- ['J DE INF B.RIVADAVIA - NUFLO DE AGUILAR 541 CAPITAL - CORDOBA', '3', '0819 a 0821', '1.038']
Contador inicial: 346
348 -- ['JOSE LUIS SERCIC - PEREZ CORREA 1500 B° M DE SOBREMONTE - CORDOBA', '8', '0822 a 0829', '2.768']
Contador inicial: 348
361 -- ['IPEM 338 - FRANCISCO SUAREZ 3760 B°M SE SOBREMONTE - CORDOBA', '8', '0830 a 0837', '2.764']
Contador inicial: 361
367 -- ['ESC JORGE NEWBERY - ALBERTO MACIAS 451 B°NEWBERY CAPITAL - CORDOBA', '10', '0838 a 0847', '3.414']
Contador inicial: 367
369 -- ['ESC NACIONES UNIDAS - CORTADA 8 S/N B°R.DE ESCALADA CAP - CORDOBA', '9', '0848 a 0856', '3.069']
Contador inicial: 369
371 -- ['IPEM 121 PAEZ MOLINA - ORIGONE ESQ CAROLA LORENZINI B°J LUIS DE CABRERA', '5', '0857 a 0861', '1.705']
Contador inicial: 371
377 -- ['ESC GOBERNADOR MANUEL LOPEZ - URQUIZA 4800 IPV ANEXO-M FRAGUEIR -', '7', '0862 a 0868', '2.443']
Contador inicial: 377
379 -- ['ESC ARTURO CAPDEVILA - AVELLANEDA 4100 B°M.FRAGUEIRO CAPIT - CORDOBA', '12', '0869 a 0880', '4.178']
Contador inicial: 379
381 -- ['ESC FRANCISCO VIDAL - MARCOS INFANTES 560 B° PANAMERICANO CAP -', '12', '0881 a 0892', '4.176']
Contador inicial: 381
383 -- ['IPEM 199 "JUAN EMILIO REMONDA" - SOSA REVELLO 590 B° FRAGUEIRO CAPITAL -', '6', '0893 a 0898', '2.088']
Contador inicial: 383
389 -- ['ESC RABINDRANAT TAGORE - OCARINA - 1613 B°V.CLAUDINA CAPITAL - CORDOBA', '3', '0899 a 0901', '774']
Contador inicial: 389
395 -- ['ESC EMILIO E SANCHEZ - ANTONIO MACHONI 1700 CAPITAL - CORDOBA', '12', '0902 a 0913', '4.197']
Contador inicial: 395
401 -- ['ESC FRAY J A DE SAN ALBERTO - ESQUIU 1340 B° PUEYRREDON CAPIT - CORDOBA', '7', '0914 a 0920', '2.448']
Contador inicial: 401
403 -- ['INST OBISPO CAIXAL - ANA M JANER 1250 B°PUEYRREDON CAPITAL - CORDOBA', '8', '0921 a 0928', '2.792']
Contador inicial: 403
405 -- ['ESC DEAN FUNES - ANA M JANER 1551 B°PUEYRREDON CAPITAL - CORDOBA', '10', '0929 a 0938', '3.490']
Contador inicial: 405
407 -- ['INST SAGRADO CORAZON - ROMA 1153 B°PUYRREDON CAPITAL - CORDOBA', '10', '0939 a 0948', '3.490']
Contador inicial: 407
409 -- ['ESC ROBLES - PADRE LUIS MONTI 1850 B°PUYRREDON CAPITAL - CORDOBA', '13', '0949 a 0961', '4.537']
Contador inicial: 409
411 -- ['INST SAGRADA FAMILIA - BUCHARDO 1675 B°PUYRREDON CAPITAL - CORDOBA', '9', '0962 a 0970', '3.141']
Contador inicial: 411
417 -- ['ESC TRINIDAD MORENO(IPEM 174) - EDUARDO SAN MARTIN 1282 B°YOFRE SUD', '12', '0971 a 0982', '4.054']
Contador inicial: 417
419 -- ['ESC ALMIRANTE BROWN - SAN MARTIN S/N° B°YOFRE SUD - CORDOBA', '13', '0983 a 0995', '4.381']
Contador inicial: 419
437 -- ['ESC PROVINCIA DE CORRIENTES - DOMINGO ZIPOLI 1358 B°ESCOBAR CAPITAL -', '8', '0996 a 1003', '2.752']
Contador inicial: 437
439 -- ['INST ESCUTI - NAZARET - 3399 B°LAS ROSAS CAPITAL - CORDOBA', '9', '1004 a 1012', '3.088']
Contador inicial: 439
445 -- ['ESC MAHATMA GANDHI - TALAVERA DE MADRID 3261 B°LA FRANCE CAPITAL -', '7', '1013 a 1019', '2.321']
Contador inicial: 445
447 -- ['COL PQUIAL C NAMUNCURA - DIAGUITAS 3314 B° LA FRANCE CAPITAL - CORDOBA', '8', '1020 a 1027', '2.648']
Contador inicial: 447
453 -- ['ESC RICARDO ROJAS (IPEM 35) - J.LOPEZ 2050 B°ALTOS DE V CABRERA -', '8', '1028 a 1035', '2.744']
Contador inicial: 453
455 -- ['ESC CONGRESO DE TUCUMAN - H MALVINO 2772 B°LAS MARGARITAS - CORDOBA', '8', '1036 a 1043', '2.737']
Contador inicial: 455
457 -- ['ESC MIGUEL RODRIGUEZ DE LA TOR - LA GRANJA 3199 B°ALTO VERDE CAPITAL -', '7', '1044 a 1050', '2.394']
Contador inicial: 457
463 -- ['ESC DE COMERCIO J J PASO - PLATON 3030 B°ZUMARAN CAPITAL - CORDOBA', '10', '1051 a 1060', '3.490']
Contador inicial: 463
465 -- ['COLEGIO FERMIN LAFITTE - FCO VALLE 2443 B°LOS PARAISOS CAPIT - CORDOBA', '10', '1061 a 1070', '3.490']
Contador inicial: 465
467 -- ['ESC JUVENILIA - ARISTOTELES 3160 B°ZUMARAN CAPITAL - CORDOBA', '7', '1071 a 1077', '2.439']
Contador inicial: 467
469 -- ['ESC PCIA DE MISIONES - FIRPO 2254 B°ZUMARAN - CORDOBA', '13', '1078 a 1090', '4.524']
Contador inicial: 469
475 -- ['COL EL SALVADOR - ROMULO CARBIA 2757 B° P LUGONES CAPITAL - CORDOBA', '8', '1091 a 1098', '2.768']
Contador inicial: 475
477 -- ['ESC LEOPOLDO LUGONES - LESPADA Y GALVEZ 2820 B°P LUGONES CAPITAL -', '10', '1099 a 1108', '3.457']
Contador inicial: 477
479 -- ['IPEM 198 MARTIN FERREYRA - JOAQUIN CAMAÑO Y BAZAN 4750 - CORDOBA', '9', '1109 a 1117', '3.105']
Contador inicial: 479
485 -- ['ESC PTE HIPOLITO YRIGOYEN - CASTRO BARROS 802 B°SAN MARTIN CAPITAL -', '15', '1118 a 1132', '5.129']
Contador inicial: 485
503 -- ['ESC ANTONIO DEL VISO - SAAVEDRA 619 B°SAN MARTIN CAPITAL - CORDOBA', '13', '1133 a 1145', '4.524']
Contador inicial: 503
505 -- ['INST INMACULADA CONCEPCION - CASTRO BARROS 1316 B°BAJO GALAN CAPITAL -', '16', '1146 a 1161', '5.563']
Contador inicial: 505
507 -- ['ESC J DE SAN MARTIN - CERRITO Y GALAN 660 B°SAN MARTIN CAPITAL - CORDOBA', '7', '1162 a 1168', '2.429']
Contador inicial: 507
509 -- ['COL NTRA SEÑORA DE LA MERCED - ZELAYA 140 B°SAN MARTIN CAPITAL -', '8', '1169 a 1176', '2.776']
Contador inicial: 509
515 -- ['INSTITUTO PEÑA - CIUDAD DE TAMPA 2954 B°VILLA CABRERA CAPI - CORDOBA', '11', '1177 a 1187', '3.751']
Contador inicial: 515
517 -- ['ESC PRESIDENTE KENNEDY - JULIAN PAZ 1851 B°VILLA CABRERA CAPT - CORDOBA', '6', '1188 a 1193', '2.042']
Contador inicial: 517
523 -- ['ESC ROQUE SAENZ PEÑA - AV VELEZ SARSFIELD 1000 B°GUEMES CAPITAL -', '14', '1194 a 1207', '4.816']
Contador inicial: 523
525 -- ['INST EDUCACION CORDOBA - MARTIN FERREYRA 216 B°COL DE V SARSFIELD -', '19', '1208 a 1226', '6.536']
Contador inicial: 525
527 -- ['E.N.E.T. N°1 DR A SABATTINI - AV VELEZ SARSFIELD 1490 B°GUEMES CAPITAL -', '9', '1227 a 1235', '3.094']
Contador inicial: 527
529 -- ['ESC MANUEL BELGRANO - SUECIA 2832 PQUE VELEZ SARSFIELD - CORDOBA', '11', '1236 a 1246', '3.773']
Contador inicial: 529
535 -- ['ESC MUN YAMAHIBIA ARABE LIBIA - COLORADO ESQ GAIMAN B° CABILDO CAPITAL', '9', '1247 a 1255', '3.122']
Contador inicial: 535
537 -- ['IPEM 311 - USUAHIA 2150 B° CABILDO - CORDOBA', '6', '1256 a 1261', '2.076']
Contador inicial: 537
543 -- ['ESC PCIA DE CATAMARCA - AV VELEZ SARSFIELD 3582 B°LAS FLORES CAPITAL -', '17', '1262 a 1278', '5.887']
Contador inicial: 543
545 -- ['ESC REPUBLICA DE SIRIA - TRAFUL 908 B° PQUE ATLANTICA - CORDOBA', '6', '1279 a 1284', '2.076']
Contador inicial: 545
547 -- ['ESC GDOR J B BUSTOS - CACHEUTA Y BRANDAN- B° ALTO VELEZ SARSFI -', '11', '1285 a 1295', '3.806']
Contador inicial: 547
549 -- ['J DE INF REPUBLICA DE SIRIA - VIRGILIO MOYANO 830 B° RESIDENCIAL VELEZ -', '1', '1296 a 1296', '346']
Contador inicial: 549
555 -- ['ESC ALEJANDRO CARBO - ICHO CRUZ 80 B° COMERCIAL CAPITAL - CORDOBA', '16', '1297 a 1312', '5.480']
Contador inicial: 555
557 -- ['ESC MUNIC AZOR GRIMAUT - SOBREMONTE 6100 B°COMERCIAL CAPITAL -', '5', '1313 a 1317', '1.710']
Contador inicial: 557
574 -- ['ESC MUNIC REPUBLICA DE ITALIA - REALICO 2250 B°CONGRESO CAPITAL -', '7', '1318 a 1324', '2.323']
Contador inicial: 574
576 -- ['IPEM 183"PEDRO B.PALACIOS" - REALICO - 2407 B°CONGRESO CAPITAL - CORDOBA', '4', '1325 a 1328', '1.324']
Contador inicial: 576
582 -- ['ESC CADETES FUERZA AEREA - LEOPOLDO CASAVEGA 2320 VILLA ADELA CAPITAL', '11', '1329 a 1339', '3.776']
Contador inicial: 582
584 -- ['ESC PADRE BURON - AVIADOR MIRA 2658 B°VILLA ADELA CAPITA - CORDOBA', '8', '1340 a 1347', '2.744']
Contador inicial: 584
586 -- ['J DE INF CADETES FUERZA AEREA - LEOPOLDO CASAVEGA 2320 B° VILLA ADELA -', '2', '1348 a 1349', '686']
Contador inicial: 586
588 -- ['ESC ALAS ARGENTINA - BONN 4627 B°ESTACION FLORES - CORDOBA', '12', '1350 a 1361', '4.116']
Contador inicial: 588
590 -- ['ESC MUNIC CESAR E ROMERO - AV ROSARIO DEL DORADO 6052 B°SACCHI CAPITAL', '7', '1362 a 1368', '2.401']
Contador inicial: 590
596 -- ['ESC AERONAUTICA ARGENTINA - ESMERALDA ESQ DIAZ DE LA FUENTE B°', '10', '1369 a 1378', '3.420']
Contador inicial: 596
598 -- ['COL NUESTRA SEÑORA DE FATIMA - VARELA ORTIZ 2600 B°MATIENZO CAPITAL -', '13', '1379 a 1391', '4.446']
Contador inicial: 598
600 -- ['ESC REPUBLICA ARGENTINA - VARELA ORTIZ 2112 B°AMEGHINO(S)CAPITAL -', '7', '1392 a 1398', '2.393']
Contador inicial: 600
602 -- ['ESC MIGUEL A ZABALA ORTIZ - DIAZ DE LA FUENTE 3101 B!MATIENZO CAPITAL -', '8', '1399 a 1406', '2.728']
Contador inicial: 602
608 -- ['E.N.E.T. N° 4 COPERNICO - MARIANO MORENO 551 B°OBSERVATORIO CAP -', '26', '1407 a 1432', '9.100']
Contador inicial: 608
610 -- ['EE UU DE NORTEAMERICA - LA PAMPA 550 B°PASOS DE LOS ANDES - CORDOBA', '9', '1433 a 1441', '3.142']
Contador inicial: 610
612 -- ['COL NUESTRA SEÑORA DE NIEVA - AYACUCHO 442 B° GUEMES CAPITAL -', '18', '1442 a 1459', '6.282']
Contador inicial: 612
614 -- ['ESC ADOLFO SALDIAS - BOLIVAR 896 B°GUEMES CAPITAL - CORDOBA', '8', '1460 a 1467', '2.792']
Contador inicial: 614
620 -- ['ESC GDOR EMILIO OLMOS - AV FUERZA AEREA 2229 B° PQUE CAPITAL - CORDOBA', '10', '1468 a 1477', '3.460']
Contador inicial: 620
622 -- ['ESC R ESCALADA DE SAN MARTIN - ESPORA 2283 B°ROSEDAL CAPITAL - CORDOBA', '13', '1478 a 1490', '4.498']
Contador inicial: 622
624 -- ['ESC MUNIC DR A DEL CASTILLO - OCTAVIANO NAVARRO 2575 B°AMPL ROSEDAL', '7', '1491 a 1497', '2.422']
Contador inicial: 624
626 -- ['IPEM 154 MARTIN M DE GUEMES - O NAVARRO 2751 ROSEDAL ANEXO CAPIT -', '6', '1498 a 1503', '2.076']
Contador inicial: 626

In [36]:
print(discontinuidades)
print("Establecimientos:", len(escuelas))
print("Discontinuidades:", len(discontinuidades))
print("Última mesa:", last_mesa)
for d in discontinuidades:
    print(d)

[{'linea': 2003, 'esperada': 4116, 'encontrada': 4117, 'establecimiento': 'IPEM N° 253 - ALEM ESQ DOMINGO MATEU CRUZ DEL EJE - CRUZ DEL EJE'}, {'linea': 2428, 'esperada': 4434, 'encontrada': 4436, 'establecimiento': 'ESCUELA J.MARMOL - NAC. UNIDAS 385 VILLA MARIA - VILLA MARIA'}, {'linea': 3732, 'esperada': 6064, 'encontrada': 6065, 'establecimiento': 'ESC NICOLAS AVELLANEDA - VICENTE LOPEZ 538 PUEBLO ALBERDI - RIO CUARTO'}]
Establecimientos: 1224
Discontinuidades: 3
Última mesa: 8750
{'linea': 2003, 'esperada': 4116, 'encontrada': 4117, 'establecimiento': 'IPEM N° 253 - ALEM ESQ DOMINGO MATEU CRUZ DEL EJE - CRUZ DEL EJE'}
{'linea': 2428, 'esperada': 4434, 'encontrada': 4436, 'establecimiento': 'ESCUELA J.MARMOL - NAC. UNIDAS 385 VILLA MARIA - VILLA MARIA'}
{'linea': 3732, 'esperada': 6064, 'encontrada': 6065, 'establecimiento': 'ESC NICOLAS AVELLANEDA - VICENTE LOPEZ 538 PUEBLO ALBERDI - RIO CUARTO'}

In [37]:
print("Electores:", sum(e["electores"] for e in escuelas))

Electores: 2946060

#Dataframe

In [41]:
df_escuelas = pd.DataFrame(escuelas)

display(df_escuelas.head())
display(df_escuelas.tail())

print(df_escuelas.shape)

,seccion_nro,seccion_name,circuito_nro,circuito_name,establecimiento,cant_mesas,desde,hasta,electores
0,1,CAPITAL,1,SECCIONAL PRIMERA,CENTRO EDUC.NIVEL MEDIO ADULTO - DEAN FUNES 41...,7,1,7,2415
1,1,CAPITAL,1,SECCIONAL PRIMERA,ESC NUESTRA SEÑORA DEL HUERTO - BELGRANO 269 C...,12,8,19,4128
2,1,CAPITAL,1,SECCIONAL PRIMERA,COL NAC DE MONSERRAT - OBISPO TREJO 294 CAPITA...,18,20,37,6192
3,1,CAPITAL,1,SECCIONAL PRIMERA,ESC SANTA TERESA DE JESUS - OBISPO TREJO Y SAN...,10,38,47,3440
4,1,CAPITAL,2,SECCIONAL SEGUNDA,ESC JUAN BAUTISTA ALBERDI - GRAL PAZ 488 CAPIT...,18,48,65,6176

,seccion_nro,seccion_name,circuito_nro,circuito_name,establecimiento,cant_mesas,desde,hasta,electores
1219,26,UNION,397A,CORRAL DEL BAJO,ESCUELA VALENTIN ALSINA - CALLE PUBLICA S/N 0 ...,1,8735,8735,5
1220,26,UNION,400,SAN MARCOS SUD,INST JOSE DE SAN MARTIN - ENTRE RIOS 977 SAN M...,5,8736,8740,1605
1221,26,UNION,400,SAN MARCOS SUD,ESC PROV M BUCHARDO - PASAJE AURORA LLANOS DE ...,4,8741,8744,1283
1222,26,UNION,401,SANTA MARIA,ESC PROV PAULA ALBARRACIN - LOS FRESNOS 290 SA...,1,8745,8745,276
1223,26,UNION,402,VIAMONTE,INSTITUTO JUAN B ALBERDI - AVELLANEDA 182 VIAM...,5,8746,8750,1666

(1224, 9)

In [42]:
df_escuelas.sample(20, random_state=42)

,seccion_nro,seccion_name,circuito_nro,circuito_name,establecimiento,cant_mesas,desde,hasta,electores
661,11,POCHO,144,CHANCANI,ESC PROV MARIANO MORENO - PUBLICA S/N CHANCANI...,3,5241,5243,1045
220,1,CAPITAL,11K,VILLA GRAL URQUIZA,ESC MUNIC JUAN B JUSTO - INT RAMON B MESTRE S/...,7,2100,2106,2450
155,1,CAPITAL,10I,PARQUE HORIZONTE,PRIMARIA ELPIDIO TORRES - CALLE PUBLICA S/N SM...,12,1504,1515,4200
677,12,PUNILLA,148,CAPILLA DEL MONTE,ESC ESP JUAN MANUEL FERNANDEZ - AV PUEYRREDON ...,10,5312,5321,3460
911,17,ROQUE SAENZ PEÑA,248,LABOULAYE,I.P.E.M. 278-M.ARGENTINAS - AV INDEPENDENCIA 4...,9,6868,6876,3123
168,1,CAPITAL,10L,VILLA EL LIBERTADOR,ESC PTE DR ARTURO U ILLIA - TOTORAL Y ARICA B°...,11,1621,1631,3817
1087,21,SANTA MARIA,322,COSME,ESC PROV OLEGARIO V ANDRADE - PUBLICA S/N COSM...,1,7953,7953,51
113,1,CAPITAL,9C,LOS PARAISOS,ESC PCIA DE MISIONES - FIRPO 2254 B°ZUMARAN - ...,13,1078,1090,4524
605,9,MARCOS JUAREZ,119,ALEJO LEDESMA,INSTITUTO SEC. V.SARSFIELD - HIPILITO YRIGOYEN...,4,4955,4958,1284
536,6,GRAL SAN MARTIN,88,TIO PUJIO,ESC.R.DE ESCALADA - 25 DE MAYO 84 NORTE TIO PU...,10,4424,4433,3312
830,14,RIO PRIMERO,207,LAS SALADAS,ESC DALMIRA MURO(EX DEL CHACO) - LAS SALADAS L...,1,6439,6439,267
381,2,CALAMUCHITA,23,VILLA YACANTO,IPEM 390 - TUCUMAN S/N VILLA YACANTO - VILLA Y...,6,3351,3356,1916
718,12,PUNILLA,156D,SAN ANTONIO DE ARREDONDO,ESC JUAN JOSE PASO - RUTA PROV. 14-KM.43 CENTR...,8,5669,5676,2680
594,8,JUAREZ CELMAN,111,HUANCHILLA,ESC PROV DOMINGO F SARMIENTO - CARLOS ALBERTO ...,4,4885,4888,1187
107,1,CAPITAL,9B,LAS MARGARITAS,ESC RICARDO ROJAS (IPEM 35) - J.LOPEZ 2050 B°A...,8,1028,1035,2744
572,7,ISCHILIN,97,ISCHILIN,ESCUELA FERNANDO FADER - PUBLICA S/N ISCHILIN ...,1,4772,4772,84
900,16,RIO SEGUNDO,243,RIO SEGUNDO,ESC PRIMER GOBIERNO PATRIO - RIVADAVIA 915 RIO...,12,6774,6785,4140
361,2,CALAMUCHITA,16A,VILLA LA MERCED,ESCUELA N° 404 - VILLA LA MERCED VILLA LA MERC...,1,3267,3267,88
713,12,PUNILLA,156,VILLA CARLOS PAZ,COLEGIO COSTA AZUL - HUARPES Y COMECHINGONES-B...,13,5640,5652,4517
622,9,MARCOS JUAREZ,127,GUATIMOZIN,ESC DALMACIO VELEZ SARSFIELD - AV CORDOBA 324 ...,6,5052,5057,2064

In [43]:
output_path = "escuelas-elecciones-2019-cordoba.csv"

df_escuelas.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

print(f"Archivo exportado: {output_path}")

Archivo exportado: escuelas-elecciones-2015-cordoba.csv